### ISSUE TITLE
Feature: User can view the category of plants

### ISSUE THREAD

**Issue by twoosam** [twoosam/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the category of plants.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking the catalog, the user will be presented with 3 clickable categories of the type product being sold.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/twoosam/Final-Project/assets/123339845/0bf380de-5c28-451d-9774-c0391e16ebae)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to insert into "category" table.
- [x] Add the names of the columns which will be "name" and "imageUrl"
- [x] Add the values which will be whatever you want to correspond for the above column names. 

### ☁️ Server Tasks

- [x] Update `server.js` with a GET request to '/api/category'
- [x] The second parameter of the GET will be an async function with req, res, and next as its' parameters.
- [x] Create a try catch within the function that will select the data from the tables.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to show the navbar
- [x] Create a component to show the catalog

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
